// Seed_Names.js
// Seznam předefinovaných textů pro seed tlačítko

export const SEED_NAMES = [
  "RVDA smrdí",
  "Hrošík pije pívo",
  "Gorila ztratil banán",
  "Dodův jogurt",
  "Východní křídlo",
  "Sloven..maďarská klobása",
  "Rychlejší jak e-mail",
  "Omnissiah",
  "NEXIA AP a.s.",
  "Komárku štípl komár",
  "Pronikající smích",
  "Vláďa odchází",
  "Petrův Zdeněk",
  "Jsem slabej",
  "Chytrej Honza",
  "Ondrůj župan",
  "RVDA je banda volů",
  "Pochcané RVDA",
  "Hluboký lidský příběh",
  "Jestli mi teda jako rozumíte",
  "Metodika je pro amatéry",
  "Běháme pro radost",
  "Lord Voldemort",
  "Michalova deprese",
  "SkokyTime",
  "Točí tady někdu tu Plzeň?",
  "Kdo to tady šéfuje?",
  "Duševní vlastnictví Toma",
  "Polib si elipsi",
  "Ještě že nejsem na Slovensku",
  "Všichni tady zemřeme",
];
